# Generated by Django 5.2.8 on 2025-12-08 10:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.customer'),
        ),
        migrations.AddField(
            model_name='sale',
            name='transaction_type',
            field=models.CharField(choices=[('Sold', 'Sold'), ('Bought', 'Bought')], default='Sold', max_length=7),
        ),
    ]
